version: '3.8'

# ==============================================================================
# HunyuanImage-3.0 Docker Compose 配置
# ==============================================================================

services:
  # 主服务: HunyuanImage-3.0 API
  hunyuan-api:
    image: hunyuan-image-3.0:latest
    container_name: hunyuan-api
    command: api  # 可选: api, cli, bash

    # 端口映射
    ports:
      - "8000:8000"  # API服务端口

    # 卷挂载
    volumes:
      - ./outputs:/app/outputs          # 生成的图片输出目录
      # - ./custom-models:/app/models   # 可选: 自定义模型路径

    # GPU配置
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all                 # 使用所有GPU
              # count: 2                 # 或指定GPU数量
              # device_ids: ['0', '1']   # 或指定GPU ID
              capabilities: [gpu]

    # 环境变量（可选）
    environment:
      - CUDA_VISIBLE_DEVICES=0,1,2,3     # 指定可见的GPU设备
      # - PYTHONUNBUFFERED=1
      # - LOG_LEVEL=info

    # 资源限制（可选）
    # mem_limit: 64g
    # memswap_limit: 128g
    # cpus: 16

    # 重启策略
    restart: unless-stopped

    # 日志配置
    logging:
      driver: "json-file"
      options:
        max-size: "100m"   # 单个日志文件最大100MB
        max-file: "5"      # 保留最近5个日志文件

    # 健康检查
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

    # 网络模式
    # network_mode: host  # 如果需要使用宿主机网络

# ==============================================================================
# 可选服务配置
# ==============================================================================

  # Nginx反向代理（可选）
  # nginx:
  #   image: nginx:latest
  #   container_name: hunyuan-nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./ssl:/etc/nginx/ssl:ro
  #   depends_on:
  #     - hunyuan-api
  #   restart: unless-stopped

# ==============================================================================
# 网络配置（可选）
# ==============================================================================

# networks:
#   hunyuan-net:
#     driver: bridge

# ==============================================================================
# 卷配置（可选）
# ==============================================================================

# volumes:
#   hunyuan-outputs:
#     driver: local
